// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwRSZHuPDI5iTTaAy8muGvycdiUlVW2Us',
    appId: '1:874203924152:web:8428d029c48767b6fbd64d',
    messagingSenderId: '874203924152',
    projectId: 'trysomethingforfl',
    authDomain: 'trysomethingforfl.firebaseapp.com',
    storageBucket: 'trysomethingforfl.appspot.com',
    measurementId: 'G-PJ4VQFDW4R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA25kH9RtRcWRLASqq4yqOBZhwiZtjEqzc',
    appId: '1:874203924152:android:ca47607af4e63e4cfbd64d',
    messagingSenderId: '874203924152',
    projectId: 'trysomethingforfl',
    storageBucket: 'trysomethingforfl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6bFRrywh2eH3QPNXVY_o-OJyYcL0saPA',
    appId: '1:874203924152:ios:e15ec9b63d66051bfbd64d',
    messagingSenderId: '874203924152',
    projectId: 'trysomethingforfl',
    storageBucket: 'trysomethingforfl.appspot.com',
    iosClientId: '874203924152-bgafjjrrvti4mdvieraqddgqdn0fuhe2.apps.googleusercontent.com',
    iosBundleId: 'com.example.trySomething',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6bFRrywh2eH3QPNXVY_o-OJyYcL0saPA',
    appId: '1:874203924152:ios:80e25c1f8cea2910fbd64d',
    messagingSenderId: '874203924152',
    projectId: 'trysomethingforfl',
    storageBucket: 'trysomethingforfl.appspot.com',
    iosClientId: '874203924152-1gjpfl489m193tqn60eb5t2ag1h0n8kg.apps.googleusercontent.com',
    iosBundleId: 'com.example.trySomething.RunnerTests',
  );
}
